name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: |
            cp config.yaml.example config.yaml
            lein test
            lein check-idiomatic
            lein check-format
    - name: Compile jar
      run: |
            lein uberjar
    - name: Dist jar
      run: |
            mkdir -p dist
            cp target/*.jar dist

