name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: |
            cp config.yaml.example config.yaml
            lein test
            lein check-idiomatic
            lein check-format
    - name: Compile jar
      run: |
            lein uberjar
    - name: Dist jar
      run: |
            mkdir -p dist
            rm -r dist/
            mkdir -p dist
            cp target/*.jar dist
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git add -f dist
            git commit -m 'Update dist'
            git push origin master
